fix editing
svitlana2299/Nagini_team pull request #24
Opened 2023-06-05 09:24 UTC by Siia95

2023-06-05 09:31 UTC, Alexey-Goryachev requested changes
пока не ок , вывод данных не очень как то , плюс при повторном запросе edit  не хочет давать менять данные ,
 
 How can I help you?
add
Name: alex
Phone (add data in format '+38 number phone' or 'number phone'): 
Birthday(enter data in the format dd-mm-year): 
Email: 
Address(enter data in the format "name street" "number building" "name town"): 
Contact added successfully
How can I help you?
show all
[{'name': Alex}]
How can I help you?
edit
You have entered an invalid command, please refine your query
How can I help you?
edit alex
True Alex Alex
name: alex
phones: 0959169001
Name can not be empty, please repeat the command and enter correct user name, or enter next command

You have entered an invalid command, please refine your query
How can I help you?
show all
[{'name': alex}]
How can I help you?
edit 
You have entered an invalid command, please refine your query
How can I help you?
edit alex
False alex Alex
Name can not be empty, please repeat the command and enter correct user name, or enter next command

2023-06-05 09:52 UTC, Siia95 commented
Якщо вводиться edit, то імʼя має бути написао так само, як і при збереженні контакту. Так як нейм - це ключ, він унікальний і не може бути регістронезалежним. 
Команда edit без імені - не працює, так як бот не розумію, щор треба редагувати. 
Уточни, будь ласка, що значить "Вивод даних не оч".

2023-06-05 10:01 UTC, Alexey-Goryachev commented
вот пример с одинаковым именем , все равно не совсем вывод 
show all
[{'name': Alex}]
How can I help you?
edit Alex
True Alex Alex
name:
phones: 0959169001
Name can not be empty, please repeat the command and enter correct user name, or enter next command
edit
You have entered an invalid command, please refine your query
How can I help you?
edit Alex
True Alex Alex
name: Alex
phones: 0673217629
Name can not be empty, please repeat the command and enter correct user name, or enter next command

2023-06-05 14:45 UTC, Siia95 commented
Змінено: 
read, search, edit, remove

read: читає і видає інфсу, яка була збережена через команду save (окремий файл contacts_data.csv)
search: шукає контакт по імені (регістронезалежний, шукає всі контакти, в імені яких є те, що ти написав).
edit: редагує контакт по імені. Якщо телефон існує - пропонує вказати, який з телефонів хочеш змінити. Обираєш його, через пробіл пишеш новий і клікаєш ентер. Якщо не хочеш редагувати телефон - просто пропускаєш поле. 
remove: видаляє контакт по імені. 
Всі, хто до цього пробував цю гілку - видаліть її з локалу, будь ласка, і витягніть наново!

2023-06-05 15:06 UTC, Alexey-Goryachev commented
У меня вот так сейчас :
show all
-----------------------------------------------------------
name: Alex
-----------------------------------------------------------
How can I help you?

edit Alex
name: Alex
Name can not be empty, please repeat the command and enter correct user name, or enter next command
edit Alex
name: 
Name can not be empty, please repeat the command and enter correct user name, or enter next command

You have entered an invalid command, please refine your query
How can I help you?

Или я что то не так ввожу?

2023-06-05 21:17 UTC, Alexey-Goryachev commented
Фиксирую  что обсудили на митинге ,
1)Доработать формат  внесения и сохранения даты birthday, утвердили что данные  в адресной книге сохраняем строкой в виде 'дд-мм-гоод'
2)Доработать валидацию  при изменениях email, утвердили чтоб формат email был  стандартный общепринятый .
3)Подправить сообщения и реакцию бота когда вводишь некорректное имя  пользователя при редактировании контакта, утвердили если контакта нет в записной книжке , бот должен  сообщить что данного контакта нет в записной  книге и попросить пользователя уточнить запрос.

2023-06-06 08:35 UTC, Siia95 commented
Готово:
birthday!

2023-06-06 08:40 UTC, svitlana2299 approved these changes

2023-06-06 08:55 UTC, Alexey-Goryachev approved these changes

2023-06-06 08:57 UTC, merged